<?php

$comments = json_decode('[{"username":"Donny Capnor","comment":"Donec dapibus. Duis at velit eu est congue elementum.","user_id":7,"book_id":934},
{"username":"Chris Prater","comment":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.","user_id":17,"book_id":554},
{"username":"Hazel Starrs","comment":"Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","user_id":14,"book_id":937},
{"username":"Traver Jodlowski","comment":"Nulla facilisi.","user_id":8,"book_id":801},
{"username":"Viviene Ensten","comment":"Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.","user_id":7,"book_id":171},
{"username":"Walt Conaghan","comment":"Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.","user_id":6,"book_id":284},
{"username":"Jeth Kundert","comment":"Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.","user_id":2,"book_id":215},
{"username":"Willa Youthead","comment":"Aliquam sit amet diam in magna bibendum imperdiet.","user_id":17,"book_id":120},
{"username":"Kane Abbot","comment":"Suspendisse potenti. Cras in purus eu magna vulputate luctus.","user_id":1,"book_id":613},
{"username":"Edmund Cashen","comment":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","user_id":7,"book_id":712},
{"username":"Karrie Killshaw","comment":"Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.","user_id":8,"book_id":595},
{"username":"Edyth Ledford","comment":"In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.","user_id":18,"book_id":912},
{"username":"Melvyn Capener","comment":"Duis ac nibh.","user_id":13,"book_id":722},
{"username":"Rosalia Seres","comment":"Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.","user_id":16,"book_id":190},
{"username":"Avrit Banville","comment":"Aenean fermentum. Donec ut mauris eget massa tempor convallis.","user_id":7,"book_id":417},
{"username":"Leroy Form","comment":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","user_id":4,"book_id":218},
{"username":"Thatch Coles","comment":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.","user_id":12,"book_id":334},
{"username":"Klement Davet","comment":"Fusce consequat.","user_id":14,"book_id":923},
{"username":"Alexi Albutt","comment":"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.","user_id":8,"book_id":964},
{"username":"Libby Crop","comment":"Quisque ut erat. Curabitur gravida nisi at nibh.","user_id":5,"book_id":862},
{"username":"Daren Danihelka","comment":"Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.","user_id":16,"book_id":10},
{"username":"Caron Killock","comment":"Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.","user_id":8,"book_id":759},
{"username":"Benedetta Emanuel","comment":"Quisque id justo sit amet sapien dignissim vestibulum.","user_id":16,"book_id":235},
{"username":"Nicole Southard","comment":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.","user_id":1,"book_id":350},
{"username":"Hendrika Franzetti","comment":"Nulla tellus.","user_id":10,"book_id":808},
{"username":"Meade Glede","comment":"Morbi a ipsum. Integer a nibh.","user_id":9,"book_id":278},
{"username":"Neda Towell","comment":"Etiam justo.","user_id":10,"book_id":708},
{"username":"Nerta Anespie","comment":"Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.","user_id":4,"book_id":526},
{"username":"Berny Scrooby","comment":"Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.","user_id":13,"book_id":456},
{"username":"Stephannie Lampkin","comment":"Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.","user_id":12,"book_id":391},
{"username":"Reg Eaton","comment":"Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.","user_id":15,"book_id":679},
{"username":"Ray Markushkin","comment":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.","user_id":21,"book_id":609},
{"username":"Curcio Deare","comment":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.","user_id":21,"book_id":304},
{"username":"Deb Ramsbottom","comment":"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","user_id":9,"book_id":284},
{"username":"Dalli Parish","comment":"In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.","user_id":15,"book_id":531},
{"username":"Caria McFetridge","comment":"Pellentesque at nulla.","user_id":2,"book_id":629},
{"username":"Jo-ann Brownbill","comment":"Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","user_id":13,"book_id":984},
{"username":"Frederico Carreyette","comment":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.","user_id":14,"book_id":183},
{"username":"Willie Antonov","comment":"Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.","user_id":15,"book_id":766},
{"username":"Ernie Birchett","comment":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","user_id":16,"book_id":213},
{"username":"Lucy Pavolillo","comment":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.","user_id":5,"book_id":171},
{"username":"Kori Crumbleholme","comment":"Nam dui.","user_id":21,"book_id":138},
{"username":"Cosimo Menauteau","comment":"Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.","user_id":8,"book_id":529},
{"username":"Renado Olczak","comment":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.","user_id":9,"book_id":953},
{"username":"Philip McCoy","comment":"In congue. Etiam justo.","user_id":6,"book_id":432},
{"username":"Karyn Creelman","comment":"Nullam porttitor lacus at turpis.","user_id":14,"book_id":71},
{"username":"Hedwiga Vanns","comment":"Integer tincidunt ante vel ipsum.","user_id":7,"book_id":824},
{"username":"Briana Hedgeley","comment":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","user_id":19,"book_id":557},
{"username":"Brent Rowney","comment":"Aliquam quis turpis eget elit sodales scelerisque.","user_id":17,"book_id":190},
{"username":"Linnie Thrasher","comment":"Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","user_id":16,"book_id":185},
{"username":"Marylinda Mears","comment":"Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.","user_id":7,"book_id":958},
{"username":"Kaitlyn Couttes","comment":"Phasellus in felis. Donec semper sapien a libero. Nam dui.","user_id":17,"book_id":750},
{"username":"Grant Selborne","comment":"Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.","user_id":17,"book_id":879},
{"username":"Veronika Cornelissen","comment":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","user_id":2,"book_id":366},
{"username":"Mallory Filippozzi","comment":"In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","user_id":10,"book_id":447},
{"username":"Chelsae Vitte","comment":"Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.","user_id":18,"book_id":863},
{"username":"Eolande Muzzullo","comment":"Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.","user_id":18,"book_id":945},
{"username":"Florella Workman","comment":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.","user_id":15,"book_id":485},
{"username":"Latrina Bachanski","comment":"Nulla ut erat id mauris vulputate elementum.","user_id":21,"book_id":859},
{"username":"Prentiss Grout","comment":"Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.","user_id":10,"book_id":217},
{"username":"Ingaborg Munslow","comment":"Nullam molestie nibh in lectus. Pellentesque at nulla.","user_id":12,"book_id":425},
{"username":"Sharron Follett","comment":"Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.","user_id":18,"book_id":801},
{"username":"Zelma Bullion","comment":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.","user_id":7,"book_id":341},
{"username":"Dorothee Biggin","comment":"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.","user_id":17,"book_id":902},
{"username":"Les Colliber","comment":"Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.","user_id":14,"book_id":277},
{"username":"Buckie Castella","comment":"Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.","user_id":5,"book_id":929},
{"username":"Marget Rosewarne","comment":"Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","user_id":5,"book_id":416},
{"username":"Maddy Gheerhaert","comment":"Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","user_id":9,"book_id":650},
{"username":"Damara Freiberg","comment":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.","user_id":13,"book_id":625},
{"username":"Brandy Hunnable","comment":"Morbi porttitor lorem id ligula.","user_id":15,"book_id":317},
{"username":"Anderson Engley","comment":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.","user_id":8,"book_id":647},
{"username":"Fowler Cluckie","comment":"Proin at turpis a pede posuere nonummy.","user_id":8,"book_id":510},
{"username":"Dorian Ellinor","comment":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.","user_id":16,"book_id":426},
{"username":"Gloriane Bertin","comment":"Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.","user_id":13,"book_id":166},
{"username":"Kenon Feaks","comment":"Fusce consequat.","user_id":16,"book_id":843},
{"username":"Mikkel Durdy","comment":"Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.","user_id":4,"book_id":642},
{"username":"Moyna Evemy","comment":"Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.","user_id":4,"book_id":856},
{"username":"Leeann Stubbings","comment":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.","user_id":5,"book_id":154},
{"username":"Janessa Chelsom","comment":"Ut tellus.","user_id":1,"book_id":558},
{"username":"Dav McGeechan","comment":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.","user_id":9,"book_id":563},
{"username":"Clemence Mouse","comment":"Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.","user_id":2,"book_id":869},
{"username":"Bastien Cool","comment":"Nunc purus.","user_id":16,"book_id":239},
{"username":"Ambrosio Simonnet","comment":"Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.","user_id":7,"book_id":995},
{"username":"Noni Richardt","comment":"Mauris lacinia sapien quis libero.","user_id":7,"book_id":147},
{"username":"Annabelle Benning","comment":"In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","user_id":16,"book_id":660},
{"username":"Alden Wiersma","comment":"Maecenas rhoncus aliquam lacus.","user_id":15,"book_id":140},
{"username":"Eryn Board","comment":"Vestibulum sed magna at nunc commodo placerat.","user_id":16,"book_id":75},
{"username":"Kellby Hazell","comment":"Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.","user_id":21,"book_id":585},
{"username":"Carlina Paice","comment":"In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","user_id":11,"book_id":655},
{"username":"Tracee Yule","comment":"In hac habitasse platea dictumst.","user_id":21,"book_id":793},
{"username":"Merissa Hayland","comment":"Duis ac nibh.","user_id":10,"book_id":386},
{"username":"Lalo Wilbore","comment":"Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.","user_id":21,"book_id":445},
{"username":"Kitty Handlin","comment":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.","user_id":1,"book_id":491},
{"username":"Layne Greatreax","comment":"Aenean auctor gravida sem.","user_id":6,"book_id":959},
{"username":"Kristofer De la Eglise","comment":"Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.","user_id":20,"book_id":282},
{"username":"Simmonds Robinette","comment":"Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.","user_id":14,"book_id":633},
{"username":"Chastity Evennett","comment":"Duis aliquam convallis nunc.","user_id":12,"book_id":77},
{"username":"Stefania Godilington","comment":"Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","user_id":16,"book_id":833},
{"username":"Sacha Coney","comment":"Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.","user_id":10,"book_id":205},
{"username":"Cole Ridolfi","comment":"Etiam justo.","user_id":8,"book_id":85}]', true);